const getCmmnData = () => ({
  country: [
    {
      Ctry_Currency: "XCD",
      Ctry_Latlng: "17.060816,-61.796428",
      Ctry_Code: "AG",
      Ctry_Name: "Antigua and Barbuda",
      key: "egcSeQQxKKn82xhectlD",
    },
    {
      Ctry_Code: "AU",
      Ctry_Name: "Australia",
      Ctry_Currency: "AUD",
      Ctry_Latlng: "-25.274398,133.775136",
      key: "4wsYJ8CH5rImeBDvqR6r",
    },
    {
      Ctry_Code: "BS",
      Ctry_Currency: "BSD",
      Ctry_Latlng: "25.03428,-77.39628",
      Ctry_Name: "Bahamas",
      key: "gkoX6LMh9EWbQDnVURpU",
    },
    {
      Ctry_Currency: "BZD",
      Ctry_Code: "BZ",
      Ctry_Latlng: "17.189877,-88.49765",
      Ctry_Name: "Belize",
      key: "xGbJwt4nfbJtJ073Oi22",
    },
    {
      Ctry_Name: "British Virgin Islands",
      Ctry_Latlng: "18.420695,-64.639968",
      Ctry_Code: "VG",
      Ctry_Currency: "USD",
      key: "OKl2FabpJQZUZ5UCXCJF",
    },
    {
      Ctry_Currency: "CAD",
      Ctry_Latlng: "56.130366,-106.346771",
      Ctry_Name: "Canada",
      Ctry_Code: "CA",
      key: "0JdvKo3VTr9AwBKKYTHy",
    },
    {
      Ctry_Code: "KY",
      Ctry_Latlng: "19.513469,-80.566956",
      Ctry_Name: "Cayman Islands",
      Ctry_Currency: "KYD",
      key: "d7W5sGGFbU0EC2hyu1Go",
    },
    {
      Ctry_Code: "CN",
      Ctry_Currency: "CNY",
      Ctry_Name: "China",
      Ctry_Latlng: "35.86166,104.195397",
      key: "R73JVeCBqmmWlAA5gbYI",
    },
    {
      Ctry_Latlng: "45.1,15.2",
      Ctry_Code: "HR",
      Ctry_Currency: "HRK",
      Ctry_Name: "Croatia",
      key: "vzQyFmU6BRNLHEbxUpEu",
    },
    {
      Ctry_Code: "DK",
      Ctry_Currency: "DKK",
      Ctry_Name: "Denmark",
      Ctry_Latlng: "56.26392,9.501785",
      key: "slRgz0P6d2TZ5rAb0FU4",
    },
    {
      Ctry_Code: "EE",
      Ctry_Currency: "EEK",
      Ctry_Name: "Estonia",
      Ctry_Latlng: "58.595272,25.013607",
      key: "vo68MkpNWyyhJO9sXQZh",
    },
    {
      Ctry_Latlng: "-16.578193,179.414413",
      Ctry_Name: "Fiji",
      Ctry_Currency: "FJD",
      Ctry_Code: "FJ",
      key: "4Isp8zYY02MO3awdLI7e",
    },
    {
      Ctry_Name: "Finland",
      Ctry_Currency: "EUR",
      Ctry_Latlng: "61.92411,25.748151",
      Ctry_Code: "FI",
      key: "AexdYeNGM3CUTRi3f2cJ",
    },
    {
      Ctry_Currency: "EUR",
      Ctry_Name: "France",
      Ctry_Code: "FR",
      Ctry_Latlng: "46.227638,2.213749",
      key: "pcnXmmILv4Z7KRDuzTrC",
    },
    {
      Ctry_Code: "DE",
      Ctry_Currency: "EUR",
      Ctry_Name: "Germany",
      Ctry_Latlng: "51.165691,10.451526",
      key: "BqaiTkVLK0TDj1gEXayy",
    },
    {
      Ctry_Code: "GR",
      Ctry_Latlng: "39.074208,21.824312",
      Ctry_Name: "Greece",
      Ctry_Currency: "EUR",
      key: "NpFhFZYpQZxtTljWtGlp",
    },
    {
      Ctry_Latlng: "15.199999,-86.241905",
      Ctry_Name: "Honduras",
      Ctry_Code: "HN",
      Ctry_Currency: "HNL",
      key: "TLR5hjBoTiPb1qDfODc1",
    },
    {
      Ctry_Code: "HK",
      Ctry_Currency: "HKD",
      Ctry_Name: "Hong Kong",
      Ctry_Latlng: "22.396428,114.109497",
      key: "ERpK9O3gngoIzWtD4aam",
    },
    {
      Ctry_Latlng: "41.87194,12.56738",
      Ctry_Currency: "EUR",
      Ctry_Code: "IT",
      Ctry_Name: "Italy",
      key: "ygnChqsCxG2BcI0VLkIz",
    },
    {
      Ctry_Currency: "JPY",
      Ctry_Code: "JP",
      Ctry_Latlng: "36.204824,138.252924",
      Ctry_Name: "Japan",
      key: "lWwPinptSyHtCk5p4c2f",
    },
    {
      Ctry_Name: "Madagascar",
      Ctry_Currency: "MGA",
      Ctry_Latlng: "-18.766947,46.869107",
      Ctry_Code: "MG",
      key: "j2yedeQqRCLumQop9qDl",
    },
    {
      Ctry_Latlng: "4.210484,101.975766",
      Ctry_Code: "MY",
      Ctry_Currency: "MYR",
      Ctry_Name: "Malaysia",
      key: "BMyTaddJfQye66M1V2gh",
    },
    {
      Ctry_Latlng: "23.634501,-102.552784",
      Ctry_Code: "MX",
      Ctry_Currency: "MXN",
      Ctry_Name: "Mexico",
      key: "CVcYC450K0o8fMDUrK9y",
    },
    {
      Ctry_Latlng: "52.132633,5.291266",
      Ctry_Name: "Netherlands",
      Ctry_Code: "NL",
      Ctry_Currency: "EUR",
      key: "jPLvPGTvgzKDElKPRtRk",
    },
    {
      Ctry_Latlng: "-40.900557,174.885971",
      Ctry_Currency: "NZD",
      Ctry_Name: "New Zealand",
      Ctry_Code: "NZ",
      key: "HIedlXguL1YezJIXDGKB",
    },
    {
      Ctry_Name: "Philippines",
      Ctry_Currency: "PESO",
      Ctry_Latlng: "12.879721,121.774017",
      Ctry_Code: "PH",
      key: "TYkdFznDj9bAoitjqeQS",
    },
    {
      Ctry_Name: "Portugal",
      Ctry_Currency: "EUR",
      Ctry_Code: "PT",
      Ctry_Latlng: "39.399872,-8.224454",
      key: "WACONwQkiHpGtgueR0Zx",
    },
    {
      Ctry_Currency: "RUB",
      Ctry_Name: "Russia",
      Ctry_Latlng: "61.52401,105.318756",
      Ctry_Code: "RU",
      key: "i0cEky54l0NcbCNddm01",
    },
    {
      Ctry_Latlng: "13.909444,-60.978893",
      Ctry_Code: "LC",
      Ctry_Name: "Saint Lucia",
      Ctry_Currency: "XCD",
      key: "nxVf2XZWt1RKHD29StM5",
    },
    {
      Ctry_Name: "Saint Vincent and the Grenadines",
      Ctry_Code: "VC",
      Ctry_Currency: "XCD",
      Ctry_Latlng: "12.984305,-61.287228",
      key: "PtoSzBrAnjdqXQ29w9u3",
    },
    {
      Ctry_Currency: "SGD",
      Ctry_Name: "Singapore",
      Ctry_Latlng: "1.352083,103.819836",
      Ctry_Code: "SG",
      key: "19caZInSzpYcN1BDX9o4",
    },
    {
      Ctry_Code: "KR",
      Ctry_Name: "South Korea",
      Ctry_Latlng: "35.907757,127.766922",
      Ctry_Currency: "KRW",
      key: "SmPLPcMrWOo5xCMix4My",
    },
    {
      Ctry_Currency: "EUR",
      Ctry_Name: "Spain",
      Ctry_Latlng: "40.463667,-3.74922",
      Ctry_Code: "ES",
      key: "QHF6nchGSiyhwElUMLHc",
    },
    {
      Ctry_Currency: "SEK",
      Ctry_Name: "Sweden",
      Ctry_Code: "SE",
      Ctry_Latlng: "60.128161,18.643501\t",
      key: "36vVKPxQDoeUBf9kKOxT",
    },
    {
      Ctry_Currency: "THB",
      Ctry_Latlng: "15.870032,100.992541",
      Ctry_Code: "TH",
      Ctry_Name: "Thailand",
      key: "HmIRAGHx2bloHa9lq6SJ",
    },
    {
      Ctry_Currency: "USD",
      Ctry_Code: "TC",
      Ctry_Latlng: "21.694025,-71.797928",
      Ctry_Name: "Turks and Caicos Islands",
      key: "oa3z7FWvL7X7T7GPHNqj",
    },
    {
      Ctry_Name: "U.S. Virgin Islands",
      Ctry_Currency: "USD",
      Ctry_Code: "VI",
      Ctry_Latlng: "18.335765,-64.896335",
      key: "Ez0MJffru10wegyioAsj",
    },
    {
      Ctry_Name: "U.S.A.",
      Ctry_Code: "US",
      Ctry_Currency: "USD",
      Ctry_Latlng: "37.09024,-95.712891",
      key: "St6ieUxQtcTAWGgVKAcQ",
    },
    {
      Ctry_Latlng: "23.424076,53.847818",
      Ctry_Name: "United Arab Emirates",
      Ctry_Currency: "AED",
      Ctry_Code: "AE",
      key: "xRvB7x37KsVmc5bfdADy",
    },
    {
      Ctry_Currency: "GBP",
      Ctry_Code: "GB",
      Ctry_Latlng: "55.378051,-3.435973",
      Ctry_Name: "United Kingdom",
      key: "xypkr8PqbEaUmn6y8nnn",
    },
    {
      Ctry_Code: "VN",
      Ctry_Name: "Vietnam",
      Ctry_Latlng: "14.058324,108.277199",
      Ctry_Currency: "VND",
      key: "C7qnH82AHLNS7dgvLTQm",
    },
  ],
  category: [
    {
      category_cd: 0,
      category_nm: "No Mapping",
      key: "0",
    },
    {
      category_nm: "accounting",
      category_cd: 1,
      key: "UQA17XJxDIhmEogIOiWo",
    },
    {
      category_nm: "airport",
      category_cd: 2,
      key: "xgLrNUKQPVKYodCbIOeq",
    },
    {
      category_nm: "amusement_park",
      category_cd: 3,
      key: "B4L4TOK8jr2w521ncmtm",
    },
    {
      category_cd: 4,
      category_nm: "aquarium",
      key: "aIR1qjI1244IpYrhMnWf",
    },
    {
      category_nm: "art_gallery",
      category_cd: 5,
      key: "PGqXt9BJlo3iAjrK9ehd",
    },
    {
      category_nm: "atm",
      category_cd: 6,
      key: "V26RfOUFiw7T1kS0gXkp",
    },
    {
      category_nm: "bakery",
      category_cd: 7,
      key: "mUAy8bXqynZ4xAYR50DV",
    },
    {
      category_nm: "bank",
      category_cd: 8,
      key: "ByE0ZMfFhmLdH4b9Wn9G",
    },
    {
      category_nm: "bar",
      category_cd: 9,
      key: "P4s8TeXdZiNTDJmGvU6T",
    },
    {
      category_cd: 97,
      category_nm: "beach",
      key: "eNkV1N9lBA8fSJwS2su0",
    },
    {
      category_cd: 10,
      category_nm: "beauty_salon",
      key: "8XFn9vRuMXndlJfT5Hxo",
    },
    {
      category_cd: 11,
      category_nm: "bicycle_store",
      key: "lQpQcKbioho1WQwjHEx5",
    },
    {
      category_cd: 12,
      category_nm: "book_store",
      key: "DckRSJcIWHFN94xNh0LI",
    },
    {
      category_nm: "bowling_alley",
      category_cd: 13,
      key: "OIFXMZlsd6apA5AugTnr",
    },
    {
      category_cd: 14,
      category_nm: "bus_station",
      key: "yzb5f6pVPr5TVgBf8WT5",
    },
    {
      category_nm: "cafe",
      category_cd: 15,
      key: "hefSAv6YJr8rshEvG7gl",
    },
    {
      category_cd: 16,
      category_nm: "campground",
      key: "SgojReKuF1eTfQOix8Vq",
    },
    {
      category_nm: "car_dealer",
      category_cd: 17,
      key: "NVYnhSOjxGmDbgxpxpK0",
    },
    {
      category_nm: "car_rental",
      category_cd: 18,
      key: "Eh5vvkMc0fZylwuZY8zi",
    },
    {
      category_nm: "car_repair",
      category_cd: 19,
      key: "Avr2qF6o4ii9BKewHC5B",
    },
    {
      category_nm: "car_wash",
      category_cd: 20,
      key: "ZNKNrbfoccVJapkao2kz",
    },
    {
      category_cd: 21,
      category_nm: "casino",
      key: "nKGXR77yKfbfgcyyiVQY",
    },
    {
      category_nm: "cemetery",
      category_cd: 22,
      key: "eiS9b7GC8YNAZfHJlFD6",
    },
    {
      category_cd: 23,
      category_nm: "church",
      key: "Co6okEo54v9HFwxPGIOW",
    },
    {
      category_nm: "city_hall",
      category_cd: 24,
      key: "Cqipmvd9iPbMr0yFQxcn",
    },
    {
      category_nm: "clothing_store",
      category_cd: 25,
      key: "niGmmPWXDpFDidsvfgia",
    },
    {
      category_nm: "convenience_store",
      category_cd: 26,
      key: "9sALGr3Bbzywbcif0MSx",
    },
    {
      category_cd: 27,
      category_nm: "courthouse",
      key: "UJpoHONv4TfhBd1UsE6i",
    },
    {
      category_cd: 28,
      category_nm: "dentist",
      key: "YmEpHGFKWDYdpHebBuJT",
    },
    {
      category_nm: "department_store",
      category_cd: 29,
      key: "xTXp9KOjR6iyaXslDLTh",
    },
    {
      category_cd: 30,
      category_nm: "doctor",
      key: "EIhxwxcf8400AyelyahI",
    },
    {
      category_nm: "drugstore",
      category_cd: 31,
      key: "xMvE2iuUwZ5tcJfI7o95",
    },
    {
      category_nm: "electrician",
      category_cd: 32,
      key: "7P89iUwSqH90dBvBao1n",
    },
    {
      category_nm: "electronics_store",
      category_cd: 33,
      key: "lg18IXEGc97Pit578Y8Y",
    },
    {
      category_nm: "embassy",
      category_cd: 34,
      key: "dOaklc0tvk82jlGoOqT6",
    },
    {
      category_cd: 35,
      category_nm: "fire_station",
      key: "HazZsemPWYvEa1w1bGPn",
    },
    {
      category_cd: 36,
      category_nm: "florist",
      key: "SxrXYsOnrHXcSbmZPTpu",
    },
    {
      category_cd: 37,
      category_nm: "funeral_home",
      key: "DPYyS4jTEO0DrYvSwJVc",
    },
    {
      category_nm: "furniture_store",
      category_cd: 38,
      key: "OLBAcVhyAPjc7fDcbjFE",
    },
    {
      category_cd: 39,
      category_nm: "gas_station",
      key: "DWOidsP2Q2hREdrx7Crz",
    },
    {
      category_cd: 40,
      category_nm: "gym",
      key: "YxWBWJYDmSRrLadSvXeK",
    },
    {
      category_nm: "hair_care",
      category_cd: 41,
      key: "GdBTazXkd5PFIOU7f5gK",
    },
    {
      category_cd: 42,
      category_nm: "hardware_store",
      key: "zk1igQALvh2hIixyOIl7",
    },
    {
      category_cd: 43,
      category_nm: "hindu_temple",
      key: "y2AaGo4HA0YBPy0cXcuK",
    },
    {
      category_nm: "home_goods_store",
      category_cd: 44,
      key: "9b4lDQ6wshFaNlRoZANt",
    },
    {
      category_cd: 45,
      category_nm: "hospital",
      key: "XXM6pQiB0Yd6aSvvXmrx",
    },
    {
      category_cd: 46,
      category_nm: "insurance_agency",
      key: "5B32hhkpWmkPUcFfRfwx",
    },
    {
      category_nm: "jewelry_store",
      category_cd: 47,
      key: "irhTuHqA5bzxG4asLvf3",
    },
    {
      category_nm: "laundry",
      category_cd: 48,
      key: "b2sI65hWY84GP77rZgcc",
    },
    {
      category_cd: 49,
      category_nm: "lawyer",
      key: "gqa7VVTr8csQ8GAlrIql",
    },
    {
      category_nm: "library",
      category_cd: 50,
      key: "7vcXWSeGYaATIFxnimC4",
    },
    {
      category_cd: 51,
      category_nm: "light_rail_station",
      key: "1ngxe8sO4yQKkXJx5Ugm",
    },
    {
      category_cd: 52,
      category_nm: "liquor_store",
      key: "IhbGlbNn78yORWJ5DhFm",
    },
    {
      category_nm: "local_government_office",
      category_cd: 53,
      key: "uVk6q6mgCp0G0NkpPJ3D",
    },
    {
      category_cd: 54,
      category_nm: "locksmith",
      key: "M7Ilfb7ZSAiudvruMbNf",
    },
    {
      category_cd: 55,
      category_nm: "lodging",
      key: "aMhm4RkEsFceehb0NiQS",
    },
    {
      category_cd: 56,
      category_nm: "meal_delivery",
      key: "mUFksAlpuc9WMDxTKuP1",
    },
    {
      category_cd: 57,
      category_nm: "meal_takeaway",
      key: "6onpeelMxyas4jJd3vvS",
    },
    {
      category_cd: 58,
      category_nm: "mosque",
      key: "xIerMbWARXQBoCps0KQw",
    },
    {
      category_cd: 59,
      category_nm: "movie_rental",
      key: "cDFdRZHulQPSEMOpXTpx",
    },
    {
      category_cd: 60,
      category_nm: "movie_theater",
      key: "fP1lACJfP5BAVoOGIseJ",
    },
    {
      category_cd: 61,
      category_nm: "moving_company",
      key: "OBkG8loS6kvH3XFnGcwx",
    },
    {
      category_cd: 62,
      category_nm: "museum",
      key: "wNXnKjOTSQLoDFVUV6Rb",
    },
    {
      category_nm: "night_club",
      category_cd: 63,
      key: "rL4AZPXRjt4eDcexGIKE",
    },
    {
      category_cd: 64,
      category_nm: "painter",
      key: "mUeal6uDhODoyXZFzEXp",
    },
    {
      category_nm: "park",
      category_cd: 65,
      key: "bYUJiYxWW5eqSxnmZf7d",
    },
    {
      category_cd: 66,
      category_nm: "parking",
      key: "jEdBbg3A7TaJlZ5fxP15",
    },
    {
      category_nm: "pet_store",
      category_cd: 67,
      key: "MVtPybEFsjracr43JOql",
    },
    {
      category_nm: "pharmacy",
      category_cd: 68,
      key: "0a7TPLNvSfWazuHVEmO2",
    },
    {
      category_cd: 69,
      category_nm: "physiotherapist",
      key: "7IqrCpcxRci1GwGSS5Qm",
    },
    {
      category_cd: 70,
      category_nm: "plumber",
      key: "0Mn2BMG5UClcQhTeYsty",
    },
    {
      category_nm: "police",
      category_cd: 71,
      key: "MthGvkjtZB3EmyRViyiG",
    },
    {
      category_nm: "post_office",
      category_cd: 72,
      key: "PFYImmP7NR8cv3vVxPL6",
    },
    {
      category_cd: 73,
      category_nm: "primary_school",
      key: "OK7MFFePeZA5g9U8vy3G",
    },
    {
      category_nm: "real_estate_agency",
      category_cd: 74,
      key: "rzWWBtZkVlRuYlb58ERu",
    },
    {
      category_nm: "restaurant",
      category_cd: 75,
      key: "XEaCyA9Gdyc4P5cLVmSy",
    },
    {
      category_nm: "roofing_contractor",
      category_cd: 76,
      key: "wJcZWJZ9ToJ5JMYHbloi",
    },
    {
      category_cd: 77,
      category_nm: "rv_park",
      key: "gNtru9CtOCr3lDAkYx7T",
    },
    {
      category_cd: 78,
      category_nm: "school",
      key: "mrF6bvHsM1V2MfDC2xJj",
    },
    {
      category_cd: 79,
      category_nm: "secondary_school",
      key: "UukWh9Pmw7xjvtdlC8Wx",
    },
    {
      category_cd: 80,
      category_nm: "shoe_store",
      key: "NWG8lQ13YogFc6CfvktK",
    },
    {
      category_cd: 81,
      category_nm: "shopping_mall",
      key: "rxnkaVDIX7HfBSW4JuWy",
    },
    {
      category_nm: "spa",
      category_cd: 82,
      key: "vbLdVoooCzQhWZY9HsBb",
    },
    {
      category_cd: 83,
      category_nm: "stadium",
      key: "XjejDPedOeUrKk9mv8GG",
    },
    {
      category_nm: "storage",
      category_cd: 84,
      key: "RfrqfkbzuEalTIjeDJm6",
    },
    {
      category_cd: 85,
      category_nm: "store",
      key: "Q5G4vqmBtb515YnV7yRf",
    },
    {
      category_cd: 86,
      category_nm: "subway_station",
      key: "39cZNlEmosqos1wfJ9Sv",
    },
    {
      category_cd: 87,
      category_nm: "supermarket",
      key: "TkwUoJFNLtJVCWLzxfsK",
    },
    {
      category_cd: 88,
      category_nm: "synagogue",
      key: "TwiLyONhNyucaOxkOgGG",
    },
    {
      category_nm: "taxi_stand",
      category_cd: 89,
      key: "LXOWATnkTuClPgoUqaol",
    },
    {
      category_nm: "tourist_attraction",
      category_cd: 90,
      key: "eh3xJ7xovPd7z1yKvkiV",
    },
    {
      category_nm: "train_station",
      category_cd: 91,
      key: "bqH2O2R9mg1H3SpCJrlG",
    },
    {
      category_nm: "transit_station",
      category_cd: 92,
      key: "Y0ZB4pKo8BnGPGmZl0F6",
    },
    {
      category_cd: 93,
      category_nm: "travel_agency",
      key: "him6nIkTgeEUuM1P5Ms4",
    },
    {
      category_nm: "university",
      category_cd: 94,
      key: "deyV2JVZ14My9XDuVGG9",
    },
    {
      category_cd: 95,
      category_nm: "veterinary_care",
      key: "7ocyZbCeybgu5nl12p3C",
    },
    {
      category_cd: 96,
      category_nm: "zoo",
      key: "1TyLSNM52jE6fb8xRkRl",
    },
  ],
});

export default getCmmnData;
